name: hive_cache
description: Automatically persists and restores states
version: 1.0.0
# repository: https://github.com/my_org/my_repo
topics: [cache, state-management]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.3.2

dependencies:
  hive: ^2.2.3
  synchronized: ^3.1.0+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
